spring.datasource.url=jdbc:mysql://localhost:3306/superperu_db?useSSL=false&serverTimezone=America/Lima
spring.datasource.username=root
spring.datasource.password=Ache2580+.//
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080